---
- name: Configure git
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: "color.ui", value: "true" }
    - { name: "user.name", value: "{{ full_name }}" }
    - { name: "user.email", value: "{{ email }}" }

- name: Get GitHub host key
  command: ssh-keyscan -t rsa github.com
  register: github_ssh_key
  changed_when: False

- name: Add github to known hosts
  known_hosts:
    path: ~/.ssh/known_hosts
    name: github.com
    key: "{{ github_ssh_key.stdout }}"
